version: "3"
services:
  zeppelin:
    image: apache/zeppelin:0.8.1
    hostname: zeppelin
    ports:
      - "8080:8080"
    volumes:
      - /Users/hermansh/shared:/shared
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    hostname: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - /Users/hermansh/shared:/shared
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
