version: "3"
services:
  masternode:
    image: "hadoop:latest"
    ports:
      - "8020:8020"
      - "50070:50070"
      - "9000:9000"
      - "8088:8088"
    environment:
      - NAMENODE=TRUE
      - RESOURCE_MANAGER=TRUE
    volumes:
      - ./hadoop/etc:/opt/hadoop-2.8.4/etc/hadoop
  datanode1:
    image: "hadoop:latest"
    volumes:
      - ./hadoop/etc:/opt/hadoop-2.8.4/etc/hadoop
    depends_on:
      - masternode
  datanode2:
    image: "hadoop:latest"
    volumes:
      - ./hadoop/etc:/opt/hadoop-2.8.4/etc/hadoop
    depends_on:
      - masternode
  datanode3:
    image: "hadoop:latest"
    volumes:
      - ./hadoop/etc:/opt/hadoop-2.8.4/etc/hadoop
    depends_on:
      - masternode
#  nifi:
#    image: "apache/nifi:latest"
#    ports:
#      - "8080:8080"
