version: "3"
services:
  master:
    build: hadoop-node
    image: hadoop-node
    hostname: master
    ports:
      - "8020:8020"
      - "8042:8042"
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
    volumes:
      - ./hadoop-node/dirs/etc:/opt/hadoop-2.8.4/etc/hadoop
    environment:
      - NAMENODE="TRUE"
      - RESOURCE_MANAGER="TRUE"
  node:
    build: hadoop-node
    image: hadoop-node
    volumes:
      - ./hadoop-node/dirs/etc:/opt/hadoop-2.8.4/etc/hadoop
    depends_on:
      - master
  gateway:
    build: hadoop-node
    image: hadoop-node
    hostname: gateway
    volumes:
      - ./hadoop-node/dirs/etc:/opt/hadoop-2.8.4/etc/hadoop
    command: /usr/sbin/sshd -D
    ports:
      - "22:22"
  spark:
    build: hadoop-node
    image: hadoop-node
    hostname: spark
    volumes:
      - ./hadoop-node/dirs/etc:/opt/hadoop-2.8.4/etc/hadoop
    command: /usr/sbin/sshd -D

#  nifi:
#    image: "apache/nifi:latest"
#    ports:
#      - "8080:8080"
